version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: lintbot-t3-app
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
